### ISSUE TITLE
Unable to build stand-alone GDASApp

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/GDASApp#1305]
Attempts to build GDASApp outside of g-w fail while adding gw-ci tests.

Below is the error message we get when building GDASApp `devleop` at 2be1fcd on Hera as `role.jedipara`.
```
-- ---------------------------------------------------------
-- Adding bundle project gdas
-- ---------------------------------------------------------
-- ^[[32m[GDASApp] (1.0.0) [2be1fcd]^[[m
-- Feature TESTS enabled
-- Found Python3: /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/unified-env-rocky8/install/intel/2021.5.0/python-3.10.13-2p2rady/bin/python3.10 (found version "3.10.13") found components: Interpreter
Traceback (most recent call last):
  File "/scratch1/NCEPDEV/da/role.jedipara/git/GDASApp/test/bundle/gdas/test/gw-ci/get_cycles.py", line 38, in <module>
    main()
  File "/scratch1/NCEPDEV/da/role.jedipara/git/GDASApp/test/bundle/gdas/test/gw-ci/get_cycles.py", line 32, in main
    idate_value = read_idate_from_yaml(args.yaml_file)
  File "/scratch1/NCEPDEV/da/role.jedipara/git/GDASApp/test/bundle/gdas/test/gw-ci/get_cycles.py", line 8, in read_idate_from_yaml
    with open(file_path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/scratch1/NCEPDEV/da/role.jedipara/git/GDASApp/test/bundle/../../../ci/cases/pr/C48mx500_3DVarAOWCDA.yaml'
CMake Error at gdas/test/gw-ci/CMakeLists.txt:17 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  gdas/test/gw-ci/CMakeLists.txt:63 (add_cycling_tests)

...


-- Configuring incomplete, errors occurred!
See also "/scratch1/NCEPDEV/da/role.jedipara/git/GDASApp/test/build/CMakeFiles/CMakeOutput.log".
See also "/scratch1/NCEPDEV/da/role.jedipara/git/GDASApp/test/build/CMakeFiles/CMakeError.log".
```

File `/scratch1/NCEPDEV/da/role.jedipara/git/GDASApp/test/bundle/../../../ci/cases/pr/C48mx500_3DVarAOWCDA.yaml` does not exisit because this is a stand-alone clone of GDASApp.

**Comment by RussTreadon-NOAA** [comment]
As a test, move 
```
 option(RUN_GW_CI "Enable the global-workflow CI tests" OFF)
 if (RUN_GW_CI)
```
in `test/gw-ci/CMakeLists.txt` to just before
```
# Setup the environement
set(HOMEgfs ${CMAKE_SOURCE_DIR}/../../..)
set(RUNTESTS ${CMAKE_CURRENT_BINARY_DIR}/../../test/gw-ci)
```
With this change, the stand-alone GDASApp clone builds.

The modified `test/gw-ci/CMakeLists.txt` is on Hera in `/scratch1/NCEPDEV/da/role.jedipara/git/GDASApp/test`

**Comment by RussTreadon-NOAA** [comment]
Tagging @guillaumevernieres for awareness.

**Comment by guillaumevernieres** [comment]
Sorry @RussTreadon-NOAA , I completely forgot about the build case when the gdasapp is not cloned as a submodule of the g-w. What you wrote above seems fine to me.

**Comment by RussTreadon-NOAA** [comment]
Thank you @guillaumevernieres for the quick response.   I'll create a feature branch with this change.

**Comment by RussTreadon-NOAA** [comment]
The change to `test/gw-ci/CMakeLists.txt` described above will be made in [feature/gwci](https://github.com/NOAA-EMC/GDASApp/tree/feature/gwci)
