### ISSUE TITLE
GDASApp develop build fails

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/GDASApp#445]
The build for GDASApp `develop` at d34f616  fails on Hera with the following:
```
In file included from /scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/ufsda/sorc/gdas.cd/ufo/src/ufo/AnalyticInit.cc(8):
/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/ufsda/sorc/gdas.cd/oops/src/oops/interface/AnalyticInitBase.h(21): error: class "ufo::ObsTraits" has no member "SampledLocations"
    typedef typename OBS::SampledLocations SampledLocations_;
                          ^
          detected during instantiation of class "oops::interface::AnalyticInitBase<OBS> [with OBS=ufo::ObsTraits]" at line 26 of "/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/ufsda/sorc/gdas.cd/ufo/src/ufo/AnalyticInit.h"

...

/apps/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-9.2.0-wqdecm4rkyyhejagxwmnabt6lscgm45d/include/c++/9.2.0/bits/unique_ptr.h(849): error: object of abstract class type "ufo::AnalyticInit" is not allowed:
            pure virtual function "oops::interface::AnalyticInitBase<OBS>::fillGeoVaLs(const oops::interface::AnalyticInitBase<OBS>::SampledLocations_ &, oops::interface::AnalyticInitBase<OBS>::GeoVaLs_ &) const [with OBS=ufo::ObsTraits]" has no overrider
      { return unique_ptr<_Tp>(new _Tp(std::forward<_Args>(__args)...)); }
                                   ^
          detected during:
            instantiation of "std::_MakeUniq<_Tp>::__single_object std::make_unique<_Tp,_Args...>(_Args &&...) [with _Tp=ufo::AnalyticInit, _Args=<const ufo::AnalyticInit::Parameters_ &>]" at line 142 of "/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/ufsda/sorc/gdas.cd/oops/src/oops/generic/AnalyticInitBase.h"
            instantiation of "std::unique_ptr<oops::AnalyticInitMaker<OBS, T>::AnalyticInitBase_, std::default_delete<oops::AnalyticInitMaker<OBS, T>::AnalyticInitBase_>> oops::AnalyticInitMaker<OBS, T>::make(const oops::AnalyticInitParametersBase &) [with OBS=ufo::ObsTraits, T=ufo::AnalyticInit]"

compilation aborted for /scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/ufsda/sorc/gdas.cd/ufo/src/ufo/AnalyticInit.cc (code 2)
make[2]: *** [ufo/src/ufo/CMakeFiles/ufo.dir/AnalyticInit.cc.o] Error 2
make[2]: Leaving directory `/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/ufsda/sorc/gdas.cd/build'
make[1]: *** [ufo/src/ufo/CMakeFiles/ufo.dir/all] Error 2
make[1]: Leaving directory `/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/ufsda/sorc/gdas.cd/build'
make: *** [all] Error 2
```

This issue is opened to fix the build.

**Comment by RussTreadon-NOAA** [comment]
@CoryMartin-NOAA , do the nightly build logs shed any light on what's going on and/or what needs to be fixed?

**Comment by guillaumevernieres** [comment]
> @CoryMartin-NOAA , do the nightly build logs shed any light on what's going on and/or what needs to be fixed?

@RussTreadon-NOAA , we probably need to merge develop in `feature/gdasapp_ufo` ...

**Comment by RussTreadon-NOAA** [comment]
Thanks @guillaumevernieres .  I never noticed that we actually build ufo from `feature/gdasapp_ufo`.  Why?

**Comment by RussTreadon-NOAA** [comment]
As a test I switched over to ufo `develop`.   The build is still running but appears to have gotten beyond the previous error.

**Comment by guillaumevernieres** [comment]
> Thanks @guillaumevernieres . I never noticed that we actually build ufo from `feature/gdasapp_ufo`. Why?

Somebody has been procrastinating over doing a proper PR @RussTreadon-NOAA  :)

**Comment by CoryMartin-NOAA** [comment]
ha yes this is what @ADCollard keeps mentioning every week, @emilyhcliu has an upcoming PR that will allow us to switch back to develop...

**Comment by RussTreadon-NOAA** [comment]
**GDASApp build**
The build using ufo `develop` was not successful.   I merged ufo `develop` into a local copy of `feature/gdasapp_ufo` (see below).   I also updated gsibec to tag 1.1.2 given recent updates in jcsda fv3-jedi `develop`.    With these changes in place `build.sh` got further but failed in `soca` with
```
[ 94%] Building Fortran object soca/src/soca/CMakeFiles/soca.dir/AnalyticInit/soca_analytic_mod.F90.o
ifort: command line warning #10121: overriding '-qopenmp-stubs' with '-qopenmp'
/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/ufsda/sorc/gdas.cd/soca/src/soca/AnalyticInit/soca_analytic_mod.F90(11): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [UFO_LOCATIONS_MOD]
use ufo_locations_mod, only : ufo_locations
----^
/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/ufsda/sorc/gdas.cd/soca/src/soca/AnalyticInit/soca_analytic_mod.F90(29): error #6457: This derived type name has not been declared.   [UFO_LOCATIONS]
    type(ufo_locations),  intent(in) :: locs !< input locations
---------^
/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/ufsda/sorc/gdas.cd/soca/src/soca/AnalyticInit/soca_analytic_mod.F90(11): error #6580: Name in only-list does not exist or is not accessible.   [UFO_LOCATIONS]
use ufo_locations_mod, only : ufo_locations
------------------------------^
/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/ufsda/sorc/gdas.cd/soca/src/soca/AnalyticInit/soca_analytic_mod.F90(36): error #6404: This name does not have a type, and must have an explicit type.   [LOCS]
    allocate(lons(locs%nlocs()))
------------------^
/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/ufsda/sorc/gdas.cd/soca/src/soca/AnalyticInit/soca_analytic_mod.F90(36): error #6460: This is not a component name that is defined in the encompassing structure.   [NLOCS]
    allocate(lons(locs%nlocs()))
-----------------------^
/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/ufsda/sorc/gdas.cd/soca/src/soca/AnalyticInit/soca_analytic_mod.F90(36): error #6385: The highest data type rank permitted is INTEGER(KIND=8).   [LOCS]
    allocate(lons(locs%nlocs()))
------------------^
/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/ufsda/sorc/gdas.cd/soca/src/soca/AnalyticInit/soca_analytic_mod.F90(37): error #6385: The highest data type rank permitted is INTEGER(KIND=8).   [LOCS]
    allocate(lats(locs%nlocs()))
------------------^
/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/ufsda/sorc/gdas.cd/soca/src/soca/AnalyticInit/soca_analytic_mod.F90(38): error #6460: This is not a component name that is defined in the encompassing structure.   [GET_LONS]
    call locs%get_lons(lons)
--------------^
/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/ufsda/sorc/gdas.cd/soca/src/soca/AnalyticInit/soca_analytic_mod.F90(39): error #6460: This is not a component name that is defined in the encompassing structure.   [GET_LATS]
    call locs%get_lats(lats)
--------------^
/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/ufsda/sorc/gdas.cd/soca/src/soca/AnalyticInit/soca_analytic_mod.F90(43): error #6460: This is not a component name that is defined in the encompassing structure.   [NLOCS]
        do iloc = 1, geovals%geovals(ivar)%nlocs
-------------------------------------------^
/tmp/ifort08IBnd.i90: warning #6178: The return value of this FUNCTION has not been defined.   [CPTR]
compilation aborted for /scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/ufsda/sorc/gdas.cd/soca/src/soca/AnalyticInit/soca_analytic_mod.F90 (code 1)
make[2]: *** [soca/src/soca/CMakeFiles/soca.dir/AnalyticInit/soca_analytic_mod.F90.o] Error 1
make[1]: *** [soca/src/soca/CMakeFiles/soca.dir/all] Error 2
make: *** [all] Error 2
```


**`feature/gdasapp_ufo update`**
I cloned [https://github.com/JCSDA/ufo](https://github.com/JCSDA/ufo) on Hera and merged `develop` into `feature/gdasapp_ufo`.   No conflicts occurred in the merge.  May I push the updated `feature/gdasapp_ufo` to [https://github.com/JCSDA/ufo](https://github.com/JCSDA/ufo) as a short term fix.   The preferred solution is for the `feature/gdasapp_ufo` PR to be processed and we revert the ufo reference in GDASApp `CMakeLists.txt` back to `develop`.

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA if you are able to push that branch, please do, there's a chance it might be restricted now though (not sure)

**Comment by RussTreadon-NOAA** [comment]
@CoryMartin-NOAA , I am going to hold off on pushing the updated `feature/gdasapp_ufo` because the `soca` compilation error is related to `ufo`
```
 87%] Building Fortran object soca/src/soca/CMakeFiles/soca.dir/AnalyticInit/soca_analytic_mod.F90.o
ifort: command line warning #10121: overriding '-qopenmp-stubs' with '-qopenmp'
/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/ufsda/sorc/gdas.cd/soca/src/soca/AnalyticInit/soca_analytic_mod.F90(11): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [UFO_LOCATIONS_MOD]
use ufo_locations_mod, only : ufo_locations
----^
/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/ufsda/sorc/gdas.cd/soca/src/soca/AnalyticInit/soca_analytic_mod.F90(29): error #6457: This derived type name has not been declared.   [UFO_LOCATIONS]
    type(ufo_locations),  intent(in) :: locs !< input locations
---------^
/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/ufsda/sorc/gdas.cd/soca/src/soca/AnalyticInit/soca_analytic_mod.F90(11): error #6580: Name in only-list does not exist or is not accessible.   [UFO_LOCATIONS]
use ufo_locations_mod, only : ufo_locations
------------------------------^
```

**Comment by RussTreadon-NOAA** [comment]
@guillaumevernieres and @emilyhcliu , when we merge ufo `develop` into `feature/gdasapp_ufo`, the following files are renamed
```
 src/ufo/{locations_f.cc => sampled_locations_f.cc}                            |  25 +-
 src/ufo/{ufo_locations_mod.F90 => ufo_sampled_locations_mod.F90}              |  48 +--
 test/ufo/{locations_test.F90 => sampled_locations_test.F90}                   |  74 ++--
 rename src/ufo/{locations_f.cc => sampled_locations_f.cc} (56%)
 rename src/ufo/{ufo_locations_mod.F90 => ufo_sampled_locations_mod.F90} (62%)
 rename test/ufo/{locations_test.F90 => sampled_locations_test.F90} (56%)
```
`soca` files `./src/soca/AnalyticInit/soca_analytic_mod.F90` and `./src/soca/AnalyticInit/soca_analytic.interface.F90` reference `ufo_locations`.    Looks like we need to update `soca` when we update `feature/gdasapp_ufo`.   Is this an expected change?

**Comment by guillaumevernieres** [comment]
Looks like the changes were merged yesterday @RussTreadon-NOAA : https://github.com/JCSDA-internal/soca/pull/867
can you do a `git pull` under `soca`?

**Comment by RussTreadon-NOAA** [comment]
@guillaumevernieres , `git pull` in `soca` allowed `build.sh` to complete with the locally modified `ufo`.    I should redo all this in a clean GDASApp clone to ensure I can reproduce this result.

**Comment by RussTreadon-NOAA** [comment]
@guillaumevernieres .   A clean GDASApp clone and build works with the modified `ufo`.   All but one of the 29 `test_gdasapp` tests pass.   The one failure is `test_gdasapp_soca_ana_prep`.

Rerunning `test_gdasapp_soca_ana_prep` with `-VV` shows the failure to be due to 
```
1451: ============================= Testing exgdas_global_marine_analysis_prep.py for clean exit
1451: Traceback (most recent call last):
1451:   File "/scratch1/NCEPDEV/da/Russ.Treadon/git/GDASApp/work/scripts/exgdas_global_marine_analysis_prep.py", line 50, in <module>
1451:     from ufsda.stage import obs, soca_fix
1451:   File "/scratch1/NCEPDEV/da/Russ.Treadon/git/GDASApp/work/build/ush/ufsda/stage.py", line 15, in <module>
1451:     from pygw.yaml_file import YAMLFile, parse_j2yaml
1451: ImportError: cannot import name 'parse_j2yaml' from 'pygw.yaml_file' (/scratch1/NCEPDEV/da/python/opt/core/miniconda3/4.6.14/envs/gdasapp/lib/python3.7/site-packages/pygw/yaml_file.py)
```
I am not running `test_gdasapp` from within g-w.  I only cloned GDASApp.   Can we run `test_gdasapp_soca_ana_prep` directly from GDASApp?

**Comment by guillaumevernieres** [comment]
Thanks for pointing this out @RussTreadon-NOAA ... I created an issue [here](https://github.com/NOAA-EMC/GDASApp/issues/448).
I think I'm going to simply remove that test. My bad!

**Comment by RussTreadon-NOAA** [comment]
@guillaumevernieres , all 50 `test_gdasapp` PASS when GDASApp is built and run from within g-w.

@CoryMartin-NOAA , my attempt to push my working copy of `feature/gdasapp_ufo` with `develop` merged into it failed.  I don't have permission to push to `feature/gdasapp_ufo`

```
Hera(hfe11):/scratch1/NCEPDEV/da/Russ.Treadon/git/ufo/merge$ git branch
  develop
* feature/gdasapp_ufo
  master
Hera(hfe11):/scratch1/NCEPDEV/da/Russ.Treadon/git/ufo/merge$ git status
On branch feature/gdasapp_ufo
Your branch is ahead of 'origin/feature/gdasapp_ufo' by 34 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
Hera(hfe11):/scratch1/NCEPDEV/da/Russ.Treadon/git/ufo/merge$ git push origin feature/gdasapp_ufo
remote: Permission to JCSDA/ufo.git denied to RussTreadon-NOAA.
fatal: unable to access 'https://github.com/JCSDA/ufo.git/': The requested URL returned error: 403

```

**Comment by RussTreadon-NOAA** [comment]
@guillaumevernieres , I now see `icepack/` when I execute `git status` in `sorc/gdas.cd`.    We should add `icepack` to `.gitignore`

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA whoops yes I didn't catch that in G's recent PR. @guillaumevernieres do you want to add it in #447 or a separate PR?

**Comment by guillaumevernieres** [comment]
> @RussTreadon-NOAA whoops yes I didn't catch that in G's recent PR. @guillaumevernieres do you want to add it in #447 or a separate PR?

I'll do a separate PR to address the issues that @RussTreadon-NOAA identified.

**Comment by RussTreadon-NOAA** [comment]
Install a fresh clone and build of GDASApp `develop`  on Hera.   All 50 `test_gdasapp` ctests PASS when I update `gsibec` to `TAG 1.1.2`.

**Comment by RussTreadon-NOAA** [comment]
JCSDA ufo PR [#70](https://github.com/JCSDA/ufo/pull/70) merged [`develop`](https://github.com/JCSDA/ufo/tree/develop) into [`feature/gdasapp_ufo`](https://github.com/JCSDA/ufo/tree/feature/gdasapp_ufo).   While this PR allows GDASApp `develop` to successfully build, execution of `fv3jedi_var.x` with gsibec static B aborts.   
```
Run: Starting oops::Variational<FV3JEDI, UFO and IODA observations>
OOPS_STATS Variational start                        - Runtime:     3.11 sec,  Local Memory:   184.42 Mb
Exception: gsi covariance does not exist in saber::SaberCentralBlockFactory
Exception: oops::Variational<FV3JEDI, UFO and IODA observations> terminating...
```
The `develop` build echoes the following message during configuration
```
-- The following OPTIONAL packages have not been found:

 * nlohmann_json_schema_validator
 * odc (required version >= 1.0.2)
 * rttov (required version >= 12.1.0)
 * oasim
 * ropp-ufo
 * geos-aero
 * gsibec (required version >= 1.1.1)
```
gsibec tag 1.0.7 is checked out by the GDASApp `develop` build.    Changes in saber require the use of tag 1.1.1.   gsibec tag 1.1.2 is preferred since 1.1.1 was found to have some bugs.   

The structure of saber blocks changed with recent saber updates.  GDASApp ATM variational gsibec yamls need to be updated accordingly.  Updates to the gsibec tag and yamls are the subject of GDASApp issue #450.

This issue was opened to report and restore the GDASApp `develop` build.   This has been accomplished.  As such, this issue is closed.
