### ISSUE TITLE
gdasocnanalvrfy fails because of directory variable assigned to nothing

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/GDASApp#477]
gdasocnanalvrfy fails in cycling with the following:
```
Traceback (most recent call last):
  File "/scratch1/NCEPDEV/da/Andrew.Eichmann/fv3gfs/global-workflow/sorc/gdas.cd/scripts/exgdas_global_marine_analysis_vrfy.py", line 212, in <module>
    os.path.join(com_ice_history, f'{RUN}.t{gcyc}z.icef006.nc')]
  File "/scratch1/NCEPDEV/da/python/opt/core/miniconda3/4.6.14/envs/eva/lib/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
Investigation shows that while previously `com_ice_history = os.getenv('COM_ICE_HISTORY_PREV') `, `COM_ICE_HISTORY_PREV` is not assigned in the corresponding jjob JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY, whereas `COM_ICE_HISTORY` is, as follows:
`RUN=${GDUMP} YMD=${gPDY} HH=${gcyc} generate_com -rx COM_ICE_HISTORY:COM_ICE_HISTORY_TMPL`
Furthermore it seems that `COM_ICE_HISTORY_PREV` is assigned to the same thing in `JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY`, which raises the question whether they both should be one or the other.

**Comment by AndrewEichmann-NOAA** [comment]
Addressed with change to global-workflow
