### ISSUE TITLE
GDASApp @ a0616fd ctest failures

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/GDASApp#705]
Clone GDASApp @ a0616fd inside g-w on Hera and Orion.   Build GDASApp and execute `ctest -R test_gdasapp`.   51 out of 53 tests passed.  The following two tests failed on both machines.
```
        1658 - test_gdasapp_soca_JGLOBAL_PREP_OCEAN_OBS (Failed)
        1665 - test_gdasapp_land_letkfoi_snowda (Failed)
```
Rerun  thefailed tests with `-VV`.   

The soca test failed on Hera with
```
1658: running sbatch --wait run_jjobs.sh ...
1658: Traceback (most recent call last):
1658:   File "/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/timing/sorc/gdas.cd/ush/soca/run_jjobs.py", line 288, in <module>
1658:     main()
1658:   File "/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/timing/sorc/gdas.cd/ush/soca/run_jjobs.py", line 284, in main
1658:     run_card.execute(submit=True)
1658:   File "/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/timing/sorc/gdas.cd/ush/soca/run_jjobs.py", line 239, in execute
1658:     subprocess.check_output(["sbatch", "--wait", self.name])
1658:   File "/scratch1/NCEPDEV/da/python/opt/core/miniconda3/4.6.14/envs/gdasapp/lib/python3.7/subprocess.py", line 411, in check_output
1658:     **kwargs).stdout
1658:   File "/scratch1/NCEPDEV/da/python/opt/core/miniconda3/4.6.14/envs/gdasapp/lib/python3.7/subprocess.py", line 512, in run
1658:     output=stdout, stderr=stderr)
1658: subprocess.CalledProcessError: Command '['sbatch', '--wait', 'run_jjobs.sh']' returned non-zero exit status 1.
1/1 Test #1658: test_gdasapp_soca_JGLOBAL_PREP_OCEAN_OBS ...***Failed   74.35 sec
```

The land test failed on Hera with
```
1665: adpsfc_snow: read database from adpsfc_snow.nc4 (io pool size: 6)
1665: adpsfc_snow processed vars: 1 variables: totalSnowDepth
1665: adpsfc_snow assimilated vars: 1 variables: totalSnowDepth
1665: OOPS_STATS LocalEnsembleDA before solver ctor       - Runtime:     7.62 sec,  Local Memory:   258.56 Mb
1665: Exception:        Reason: An exception occurred inside ioda while opening a variable.
1665:   name:   MetaData/stationElevation
1665:   source_column:  0
1665:   source_filename:        /scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/timing/sorc/gdas.cd/ioda/src/engines/ioda/src/ioda/Has_Variables.cpp
1665:   source_function:        ioda::Variable ioda::detail::Has_Variables_Base::open(const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> &) const
1665:   source_line:    108
1665:
1665: Exception: oops::LocalEnsembleDA<FV3JEDI, UFO and IODA observations> terminating...

```
Opening this issue to alert developers.   

Feel free to close this issue if these failures are already know and fixes are being developed.

**Comment by guillaumevernieres** [comment]
Thanks @RussTreadon-NOAA , we're aware of the failing `test_gdasapp_soca_JGLOBAL_PREP_OCEAN_OBS`. @AndrewEichmann-NOAA is working on a fix.

**Comment by RussTreadon-NOAA** [comment]
**ctest follow up**

Rerun ctests from GDASApp `develop` at c501fed on Orion.   One test out of 53 failed. `test_gdasapp_soca_JGLOBAL_PREP_OCEAN_OBS` failed with the following traceback (`ctest -VV`):
```
1658: machine is orion
1658: gPDY: 20180415
1658: gcyc: 06
1658: assim_freq: 6
1658: RUN: gdas
1658: running sbatch --wait run_jjobs.sh ...
1658: Traceback (most recent call last):
1658:   File "/work2/noaa/da/rtreadon/git/global-workflow/timing/sorc/gdas.cd/ush/soca/run_jjobs.py", line 288, in <module>
1658:     main()
1658:   File "/work2/noaa/da/rtreadon/git/global-workflow/timing/sorc/gdas.cd/ush/soca/run_jjobs.py", line 284, in main
1658:     run_card.execute(submit=True)
1658:   File "/work2/noaa/da/rtreadon/git/global-workflow/timing/sorc/gdas.cd/ush/soca/run_jjobs.py", line 239, in execute
1658:     subprocess.check_output(["sbatch", "--wait", self.name])
1658:   File "/work2/noaa/da/python/opt/core/miniconda3/4.6.14/envs/gdasapp/lib/python3.7/subprocess.py", line 411, in check_output
1658:     **kwargs).stdout
1658:   File "/work2/noaa/da/python/opt/core/miniconda3/4.6.14/envs/gdasapp/lib/python3.7/subprocess.py", line 512, in run
1658:     output=stdout, stderr=stderr)
1658: subprocess.CalledProcessError: Command '['sbatch', '--wait', 'run_jjobs.sh']' returned non-zero exit status 1.
1/1 Test #1658: test_gdasapp_soca_JGLOBAL_PREP_OCEAN_OBS ...***Failed   10.19 sec
```
Rebuild GDASApp on Orion and rerun ctests.  This time `test_gdasapp_soca_JGLOBAL_PREP_OCEAN_OBS` passed but `test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY` failed. 
```
      Start 1657: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY
33/53 Test #1657: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY ....***Failed  618.39 sec
      Start 1658: test_gdasapp_soca_JGLOBAL_PREP_OCEAN_OBS
34/53 Test #1658: test_gdasapp_soca_JGLOBAL_PREP_OCEAN_OBS ..............   Passed   42.25 sec
```
Not sure why the VRFY test passed on first run but failed on the rerun.

Build GDASApp `develop` at c501fed on Hera and run ctests.  One test out of 53 failed.   `test_gdasapp_soca_JGLOBAL_PREP_OCEAN_OBS` failed with the following traceback
```
1658: machine is hera
1658: gPDY: 20180415
1658: gcyc: 06
1658: assim_freq: 6
1658: RUN: gdas
1658: running sbatch --wait run_jjobs.sh ...
1658: Traceback (most recent call last):
1658:   File "/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/timing/sorc/gdas.cd/ush/soca/run_jjobs.py", line 288, in <module>
1658:     main()
1658:   File "/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/timing/sorc/gdas.cd/ush/soca/run_jjobs.py", line 284, in main
1658:     run_card.execute(submit=True)
1658:   File "/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/timing/sorc/gdas.cd/ush/soca/run_jjobs.py", line 239, in execute
1658:     subprocess.check_output(["sbatch", "--wait", self.name])
1658:   File "/scratch1/NCEPDEV/da/python/opt/core/miniconda3/4.6.14/envs/gdasapp/lib/python3.7/subprocess.py", line 411, in check_output
1658:     **kwargs).stdout
1658:   File "/scratch1/NCEPDEV/da/python/opt/core/miniconda3/4.6.14/envs/gdasapp/lib/python3.7/subprocess.py", line 512, in run
1658:     output=stdout, stderr=stderr)
1658: subprocess.CalledProcessError: Command '['sbatch', '--wait', 'run_jjobs.sh']' returned non-zero exit status 1.
1/1 Test #1658: test_gdasapp_soca_JGLOBAL_PREP_OCEAN_OBS ...***Failed   10.30 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =  12.54 sec

```
Do others find similar behavior or get all 53 tests to pass?

**Comment by guillaumevernieres** [comment]
Thanks for testing @RussTreadon-NOAA . "vrfy" regularly runs out of time, I suspect that's the issue here too. @AndrewEichmann-NOAA , could you fix the `JGLOBAL_PREP_OCEAN_OBS` test today? 
If in a rush @RussTreadon-NOAA , we can comment out both tests. Neither are critical to the cycling (yet).

**Comment by AndrewEichmann-NOAA** [comment]
@RussTreadon-NOAA Is there a way to look at the output of this test so I don't have to wait for it to build to see what the problems is? The task ctests send stdout to a file under the test.

**Comment by guillaumevernieres** [comment]
```
/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/timing/sorc/gdas.cd/build/test/soca/gw/testrun/
```

**Comment by AndrewEichmann-NOAA** [comment]
@RussTreadon-NOAA was this build rebuilt after updating?

**Comment by RussTreadon-NOAA** [comment]
> @RussTreadon-NOAA was this build rebuilt after updating?

Yes, I rebuilt after the initial failure on Orion.   I can repeat from a fresh clone.

**Comment by AndrewEichmann-NOAA** [comment]
I'm building to replicate it now.

**Comment by guillaumevernieres** [comment]
Could it be that @AndrewEichmann-NOAA 's latest commit in the `g-w` is not in the specific commit your are using @RussTreadon-NOAA ?

**Comment by AndrewEichmann-NOAA** [comment]
> Could it be that @AndrewEichmann-NOAA 's latest commit in the `g-w` is not in the specific commit your are using @RussTreadon-NOAA ?

That looks up-to-date

**Comment by RussTreadon-NOAA** [comment]
> > Could it be that @AndrewEichmann-NOAA 's latest commit in the `g-w` is not in the specific commit your are using @RussTreadon-NOAA ?
> 
> That looks up-to-date

I'm using the current head, [8d55126b](https://github.com/NOAA-EMC/global-workflow/commit/8d55126bb0b27c79c8bee7f72b014abd34950ff9), of g-w `develop` along with the just updated head of GDASApp `develop`, 0d600e9.

**Comment by AndrewEichmann-NOAA** [comment]
I'm using the same and didn't replicate - will try with fresh clones of both

**Comment by RussTreadon-NOAA** [comment]
@AndrewEichmann-NOAA , I replicated your _no failure_ results with a fresh restart.  I did the following on Orion and Hera:
- `rm -rf gdas.cd`
- clone GDASApp `develop` @ 0d600e9 into an empty `gdas.cd`, 
- execute g-w `./build_all.sh`   (g-w `develop` at [`8d55126`](https://github.com/NOAA-EMC/global-workflow/commit/8d55126bb0b27c79c8bee7f72b014abd34950ff9)
- ./link_workflow.sh`
- load GDAS/orion modules 
- set ctest environment variables
- execute GDASApp ctests.

All 53 `test_gdasapp` _Passed_ on Orion and Hera.

_Orion_
```
(gdasapp) Orion-login-3:/work2/noaa/da/rtreadon/git/global-workflow/timing/sorc/gdas.cd/build$ ctest -R test_gdasapp
Test project /work2/noaa/da/rtreadon/git/global-workflow/timing/sorc/gdas.cd/build
      Start 1297: test_gdasapp_util_coding_norms
 1/53 Test #1297: test_gdasapp_util_coding_norms ........................   Passed    1.77 sec
      Start 1298: test_gdasapp_util_ioda_example
 2/53 Test #1298: test_gdasapp_util_ioda_example ........................   Passed    0.26 sec
      Start 1299: test_gdasapp_util_prepdata
 3/53 Test #1299: test_gdasapp_util_prepdata ............................   Passed    3.25 sec
      Start 1300: test_gdasapp_util_rads2ioda
 4/53 Test #1300: test_gdasapp_util_rads2ioda ...........................   Passed    0.16 sec
      Start 1301: test_gdasapp_util_ghrsst2ioda
 5/53 Test #1301: test_gdasapp_util_ghrsst2ioda .........................   Passed    0.18 sec
      Start 1302: test_gdasapp_util_smap2ioda
 6/53 Test #1302: test_gdasapp_util_smap2ioda ...........................   Passed    0.16 sec
      Start 1303: test_gdasapp_util_smos2ioda
 7/53 Test #1303: test_gdasapp_util_smos2ioda ...........................   Passed    0.17 sec
      Start 1304: test_gdasapp_util_icecamsr2ioda
 8/53 Test #1304: test_gdasapp_util_icecamsr2ioda .......................   Passed    0.16 sec
      Start 1635: test_gdasapp_check_python_norms
 9/53 Test #1635: test_gdasapp_check_python_norms .......................   Passed    1.13 sec
      Start 1636: test_gdasapp_check_yaml_keys
10/53 Test #1636: test_gdasapp_check_yaml_keys ..........................   Passed    0.60 sec
      Start 1637: test_gdasapp_jedi_increment_to_fv3
11/53 Test #1637: test_gdasapp_jedi_increment_to_fv3 ....................   Passed    5.39 sec
      Start 1638: test_gdasapp_convert_ewok_yaml
12/53 Test #1638: test_gdasapp_convert_ewok_yaml ........................   Passed    0.21 sec
      Start 1639: test_gdasapp_setup_cycled_exp
13/53 Test #1639: test_gdasapp_setup_cycled_exp .........................   Passed    1.10 sec
      Start 1640: test_gdasapp_convert_bufr_temp_dbuoy
14/53 Test #1640: test_gdasapp_convert_bufr_temp_dbuoy ..................   Passed    0.30 sec
      Start 1641: test_gdasapp_convert_bufr_salt_dbuoy
15/53 Test #1641: test_gdasapp_convert_bufr_salt_dbuoy ..................   Passed    0.26 sec
      Start 1642: test_gdasapp_convert_bufr_temp_mbuoyb
16/53 Test #1642: test_gdasapp_convert_bufr_temp_mbuoyb .................   Passed    0.28 sec
      Start 1643: test_gdasapp_convert_bufr_salt_mbuoyb
17/53 Test #1643: test_gdasapp_convert_bufr_salt_mbuoyb .................   Passed    0.25 sec
      Start 1644: test_gdasapp_convert_bufr_tesacprof
18/53 Test #1644: test_gdasapp_convert_bufr_tesacprof ...................   Passed    0.28 sec
      Start 1645: test_gdasapp_convert_bufr_trkobprof
19/53 Test #1645: test_gdasapp_convert_bufr_trkobprof ...................   Passed    0.26 sec
      Start 1646: test_gdasapp_convert_bufr_sfcships
20/53 Test #1646: test_gdasapp_convert_bufr_sfcships ....................   Passed    0.27 sec
      Start 1647: test_gdasapp_convert_bufr_sfcshipsu
21/53 Test #1647: test_gdasapp_convert_bufr_sfcshipsu ...................   Passed    0.26 sec
      Start 1648: test_gdasapp_soca_obsdb
22/53 Test #1648: test_gdasapp_soca_obsdb ...............................   Passed    6.07 sec
      Start 1649: test_gdasapp_soca_nsst_increment_to_mom6
23/53 Test #1649: test_gdasapp_soca_nsst_increment_to_mom6 ..............   Passed   21.38 sec
      Start 1650: test_gdasapp_soca_prep
24/53 Test #1650: test_gdasapp_soca_prep ................................   Passed    3.19 sec
      Start 1651: test_gdasapp_soca_concatioda
25/53 Test #1651: test_gdasapp_soca_concatioda ..........................   Passed    1.66 sec
      Start 1652: test_gdasapp_soca_run_clean
26/53 Test #1652: test_gdasapp_soca_run_clean ...........................   Passed    0.04 sec
      Start 1653: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP
27/53 Test #1653: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP ....   Passed   42.85 sec
      Start 1654: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT
28/53 Test #1654: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT ....   Passed   42.26 sec
      Start 1655: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_RUN
29/53 Test #1655: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_RUN .....   Passed   42.23 sec
      Start 1656: test_gdasapp_soca_copy_scratch
30/53 Test #1656: test_gdasapp_soca_copy_scratch ........................   Passed    1.38 sec
      Start 1657: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_CHKPT
31/53 Test #1657: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_CHKPT ...   Passed   42.23 sec
      Start 1658: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_POST
32/53 Test #1658: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_POST ....   Passed   10.22 sec
      Start 1659: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY
33/53 Test #1659: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY ....   Passed  362.35 sec
      Start 1660: test_gdasapp_soca_JGLOBAL_PREP_OCEAN_OBS
34/53 Test #1660: test_gdasapp_soca_JGLOBAL_PREP_OCEAN_OBS ..............   Passed   10.24 sec
      Start 1661: test_gdasapp_soca_socahybridweights
35/53 Test #1661: test_gdasapp_soca_socahybridweights ...................   Passed  202.27 sec
      Start 1662: test_gdasapp_soca_incr_handler
36/53 Test #1662: test_gdasapp_soca_incr_handler ........................   Passed   10.25 sec
      Start 1663: test_gdasapp_soca_ens_handler
37/53 Test #1663: test_gdasapp_soca_ens_handler .........................   Passed   10.20 sec
      Start 1664: test_gdasapp_land_create_ens
38/53 Test #1664: test_gdasapp_land_create_ens ..........................   Passed    2.55 sec
      Start 1665: test_gdasapp_land_imsproc
39/53 Test #1665: test_gdasapp_land_imsproc .............................   Passed    4.48 sec
      Start 1666: test_gdasapp_land_apply_jediincr
40/53 Test #1666: test_gdasapp_land_apply_jediincr ......................   Passed    3.97 sec
      Start 1667: test_gdasapp_land_letkfoi_snowda
41/53 Test #1667: test_gdasapp_land_letkfoi_snowda ......................   Passed    9.50 sec
      Start 1668: test_gdasapp_convert_bufr_adpsfc_snow
42/53 Test #1668: test_gdasapp_convert_bufr_adpsfc_snow .................   Passed    3.96 sec
      Start 1669: test_gdasapp_convert_bufr_adpsfc
43/53 Test #1669: test_gdasapp_convert_bufr_adpsfc ......................   Passed    6.57 sec
      Start 1670: test_gdasapp_convert_gsi_satbias
44/53 Test #1670: test_gdasapp_convert_gsi_satbias ......................   Passed    4.54 sec
      Start 1671: test_gdasapp_store_gsi_satbias
45/53 Test #1671: test_gdasapp_store_gsi_satbias ........................   Passed    0.64 sec
      Start 1672: test_gdasapp_setup_atm_cycled_exp
46/53 Test #1672: test_gdasapp_setup_atm_cycled_exp .....................   Passed    0.61 sec
      Start 1673: test_gdasapp_atm_jjob_var_init
47/53 Test #1673: test_gdasapp_atm_jjob_var_init ........................   Passed   45.34 sec
      Start 1674: test_gdasapp_atm_jjob_var_run
48/53 Test #1674: test_gdasapp_atm_jjob_var_run .........................   Passed  298.23 sec
      Start 1675: test_gdasapp_atm_jjob_var_final
49/53 Test #1675: test_gdasapp_atm_jjob_var_final .......................   Passed   42.21 sec
      Start 1676: test_gdasapp_atm_jjob_ens_init
50/53 Test #1676: test_gdasapp_atm_jjob_ens_init ........................   Passed  237.02 sec
      Start 1677: test_gdasapp_atm_jjob_ens_run
51/53 Test #1677: test_gdasapp_atm_jjob_ens_run .........................   Passed  298.29 sec
      Start 1678: test_gdasapp_atm_jjob_ens_final
52/53 Test #1678: test_gdasapp_atm_jjob_ens_final .......................   Passed   42.18 sec
      Start 1679: test_gdasapp_aero_gen_3dvar_yaml
53/53 Test #1679: test_gdasapp_aero_gen_3dvar_yaml ......................   Passed    0.30 sec

100% tests passed, 0 tests failed out of 53

Label Time Summary:
gdas-utils    =   6.10 sec*proc (8 tests)
script        =   6.10 sec*proc (8 tests)

Total Test time (real) = 1826.43 sec
```

_Hera_
```
(gdasapp) Hera(hfe02):/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/timing/sorc/gdas.cd/build$ ctest -R test_gdasapp
Test project /scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/timing/sorc/gdas.cd/build
      Start 1297: test_gdasapp_util_coding_norms
 1/53 Test #1297: test_gdasapp_util_coding_norms ........................   Passed    1.00 sec
      Start 1298: test_gdasapp_util_ioda_example
 2/53 Test #1298: test_gdasapp_util_ioda_example ........................   Passed    0.64 sec
      Start 1299: test_gdasapp_util_prepdata
 3/53 Test #1299: test_gdasapp_util_prepdata ............................   Passed    0.64 sec
      Start 1300: test_gdasapp_util_rads2ioda
 4/53 Test #1300: test_gdasapp_util_rads2ioda ...........................   Passed    0.38 sec
      Start 1301: test_gdasapp_util_ghrsst2ioda
 5/53 Test #1301: test_gdasapp_util_ghrsst2ioda .........................   Passed    0.16 sec
      Start 1302: test_gdasapp_util_smap2ioda
 6/53 Test #1302: test_gdasapp_util_smap2ioda ...........................   Passed    0.19 sec
      Start 1303: test_gdasapp_util_smos2ioda
 7/53 Test #1303: test_gdasapp_util_smos2ioda ...........................   Passed    0.17 sec
      Start 1304: test_gdasapp_util_icecamsr2ioda
 8/53 Test #1304: test_gdasapp_util_icecamsr2ioda .......................   Passed    0.25 sec
      Start 1635: test_gdasapp_check_python_norms
 9/53 Test #1635: test_gdasapp_check_python_norms .......................   Passed    0.88 sec
      Start 1636: test_gdasapp_check_yaml_keys
10/53 Test #1636: test_gdasapp_check_yaml_keys ..........................   Passed    0.15 sec
      Start 1637: test_gdasapp_jedi_increment_to_fv3
11/53 Test #1637: test_gdasapp_jedi_increment_to_fv3 ....................   Passed    2.76 sec
      Start 1638: test_gdasapp_convert_ewok_yaml
12/53 Test #1638: test_gdasapp_convert_ewok_yaml ........................   Passed    0.25 sec
      Start 1639: test_gdasapp_setup_cycled_exp
13/53 Test #1639: test_gdasapp_setup_cycled_exp .........................   Passed    0.49 sec
      Start 1640: test_gdasapp_convert_bufr_temp_dbuoy
14/53 Test #1640: test_gdasapp_convert_bufr_temp_dbuoy ..................   Passed    0.65 sec
      Start 1641: test_gdasapp_convert_bufr_salt_dbuoy
15/53 Test #1641: test_gdasapp_convert_bufr_salt_dbuoy ..................   Passed    0.23 sec
      Start 1642: test_gdasapp_convert_bufr_temp_mbuoyb
16/53 Test #1642: test_gdasapp_convert_bufr_temp_mbuoyb .................   Passed    0.27 sec
      Start 1643: test_gdasapp_convert_bufr_salt_mbuoyb
17/53 Test #1643: test_gdasapp_convert_bufr_salt_mbuoyb .................   Passed    0.28 sec
      Start 1644: test_gdasapp_convert_bufr_tesacprof
18/53 Test #1644: test_gdasapp_convert_bufr_tesacprof ...................   Passed    0.25 sec
      Start 1645: test_gdasapp_convert_bufr_trkobprof
19/53 Test #1645: test_gdasapp_convert_bufr_trkobprof ...................   Passed    0.26 sec
      Start 1646: test_gdasapp_convert_bufr_sfcships
20/53 Test #1646: test_gdasapp_convert_bufr_sfcships ....................   Passed    0.25 sec
      Start 1647: test_gdasapp_convert_bufr_sfcshipsu
21/53 Test #1647: test_gdasapp_convert_bufr_sfcshipsu ...................   Passed    0.25 sec
      Start 1648: test_gdasapp_soca_obsdb
22/53 Test #1648: test_gdasapp_soca_obsdb ...............................   Passed    1.84 sec
      Start 1649: test_gdasapp_soca_nsst_increment_to_mom6
23/53 Test #1649: test_gdasapp_soca_nsst_increment_to_mom6 ..............   Passed    8.88 sec
      Start 1650: test_gdasapp_soca_prep
24/53 Test #1650: test_gdasapp_soca_prep ................................   Passed    2.89 sec
      Start 1651: test_gdasapp_soca_concatioda
25/53 Test #1651: test_gdasapp_soca_concatioda ..........................   Passed    3.51 sec
      Start 1652: test_gdasapp_soca_run_clean
26/53 Test #1652: test_gdasapp_soca_run_clean ...........................   Passed    0.06 sec
      Start 1653: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP
27/53 Test #1653: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP ....   Passed  106.82 sec
      Start 1654: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT
28/53 Test #1654: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT ....   Passed   74.28 sec
      Start 1655: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_RUN
29/53 Test #1655: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_RUN .....   Passed   42.39 sec
      Start 1656: test_gdasapp_soca_copy_scratch
30/53 Test #1656: test_gdasapp_soca_copy_scratch ........................   Passed    1.01 sec
      Start 1657: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_CHKPT
31/53 Test #1657: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_CHKPT ...   Passed   42.50 sec
      Start 1658: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_POST
32/53 Test #1658: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_POST ....   Passed   74.28 sec
      Start 1659: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY
33/53 Test #1659: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY ....   Passed  395.32 sec
      Start 1660: test_gdasapp_soca_JGLOBAL_PREP_OCEAN_OBS
34/53 Test #1660: test_gdasapp_soca_JGLOBAL_PREP_OCEAN_OBS ..............   Passed  202.61 sec
      Start 1661: test_gdasapp_soca_socahybridweights
35/53 Test #1661: test_gdasapp_soca_socahybridweights ...................   Passed   74.24 sec
      Start 1662: test_gdasapp_soca_incr_handler
36/53 Test #1662: test_gdasapp_soca_incr_handler ........................   Passed   10.94 sec
      Start 1663: test_gdasapp_soca_ens_handler
37/53 Test #1663: test_gdasapp_soca_ens_handler .........................   Passed   10.23 sec
      Start 1664: test_gdasapp_land_create_ens
38/53 Test #1664: test_gdasapp_land_create_ens ..........................   Passed    1.13 sec
      Start 1665: test_gdasapp_land_imsproc
39/53 Test #1665: test_gdasapp_land_imsproc .............................   Passed    3.88 sec
      Start 1666: test_gdasapp_land_apply_jediincr
40/53 Test #1666: test_gdasapp_land_apply_jediincr ......................   Passed   10.10 sec
      Start 1667: test_gdasapp_land_letkfoi_snowda
41/53 Test #1667: test_gdasapp_land_letkfoi_snowda ......................   Passed   11.99 sec
      Start 1668: test_gdasapp_convert_bufr_adpsfc_snow
42/53 Test #1668: test_gdasapp_convert_bufr_adpsfc_snow .................   Passed    3.37 sec
      Start 1669: test_gdasapp_convert_bufr_adpsfc
43/53 Test #1669: test_gdasapp_convert_bufr_adpsfc ......................   Passed    5.78 sec
      Start 1670: test_gdasapp_convert_gsi_satbias
44/53 Test #1670: test_gdasapp_convert_gsi_satbias ......................   Passed    4.20 sec
      Start 1671: test_gdasapp_store_gsi_satbias
45/53 Test #1671: test_gdasapp_store_gsi_satbias ........................   Passed    1.23 sec
      Start 1672: test_gdasapp_setup_atm_cycled_exp
46/53 Test #1672: test_gdasapp_setup_atm_cycled_exp .....................   Passed    0.88 sec
      Start 1673: test_gdasapp_atm_jjob_var_init
47/53 Test #1673: test_gdasapp_atm_jjob_var_init ........................   Passed   43.94 sec
      Start 1674: test_gdasapp_atm_jjob_var_run
48/53 Test #1674: test_gdasapp_atm_jjob_var_run .........................   Passed  138.11 sec
      Start 1675: test_gdasapp_atm_jjob_var_final
49/53 Test #1675: test_gdasapp_atm_jjob_var_final .......................   Passed   42.46 sec
      Start 1676: test_gdasapp_atm_jjob_ens_init
50/53 Test #1676: test_gdasapp_atm_jjob_ens_init ........................   Passed   43.82 sec
      Start 1677: test_gdasapp_atm_jjob_ens_run
51/53 Test #1677: test_gdasapp_atm_jjob_ens_run .........................   Passed  266.13 sec
      Start 1678: test_gdasapp_atm_jjob_ens_final
52/53 Test #1678: test_gdasapp_atm_jjob_ens_final .......................   Passed   74.14 sec
      Start 1679: test_gdasapp_aero_gen_3dvar_yaml
53/53 Test #1679: test_gdasapp_aero_gen_3dvar_yaml ......................   Passed    0.39 sec

100% tests passed, 0 tests failed out of 53

Label Time Summary:
gdas-utils    =   3.44 sec*proc (8 tests)
script        =   3.44 sec*proc (8 tests)

Total Test time (real) = 1715.31 sec
```

**Comment by AndrewEichmann-NOAA** [comment]
@RussTreadon-NOAA Ok - so we're good?

**Comment by RussTreadon-NOAA** [comment]
> @RussTreadon-NOAA Ok - so we're good?

53 _Passed_ out of 53 tests works for me.
