### ISSUE TITLE
Permission issue for bufr2ioda_subpfl_argo_profils.py

### ISSUE THREAD

**Issue by emilyhcliu** [NOAA-EMC/GDASApp#788]
The argo converter for NSST has permission issue:

```
rwxr-x--- 1 eliu da 22073 Nov 30 10:58 bufr2ioda_acft_profiles_prepbufr.py
-rwxr-x--- 1 eliu da 12458 Nov 30 10:58 bufr2ioda_adpsfc_prepbufr.py
-rwxr-x--- 1 eliu da 17927 Nov 30 10:58 bufr2ioda_adpupa_prepbufr.py
-rwxr-x--- 1 eliu da 35649 Nov 30 10:58 bufr2ioda_conventional_prepbufr_ps.py
-rwxr-x--- 1 eliu da 26012 Nov 30 10:58 bufr2ioda_gnssro_bufr.py
-rwxr-x--- 1 eliu da 23565 Nov 30 10:58 bufr2ioda_gpsro_bufr_combined.py
-rwxr-x--- 1 eliu da 18850 Nov 30 10:58 bufr2ioda_satwind_amv_ahi.py
-rwxr-x--- 1 eliu da 19356 Nov 30 10:58 bufr2ioda_satwind_amv_goes.py
-rwxr-x--- 1 eliu da 17481 Nov 30 10:58 bufr2ioda_satwind_amv_seviri.py
-rwxr-x--- 1 eliu da 14534 Nov 30 10:58 bufr2ioda_satwind_scat.py
-rwxr-x--- 1 eliu da 20134 Nov 30 10:58 bufr2ioda_sfcshp_prepbufr.py
-rw-r----- 1 eliu da 12659 Dec  1 16:54 bufr2ioda_subpfl_argo_profiles.py
-rwxr-x--- 1 eliu da  1375 Nov 30 10:58 gen_bufr2ioda_json.py
-rwxr-x--- 1 eliu da  1352 Nov 30 10:58 gen_bufr2ioda_yaml.py
drwxr-s--- 2 eliu da  4096 Nov 30 15:49 __pycache__
-rwxr-x--- 1 eliu da  4682 Nov 30 16:41 run_bufr2ioda.py
-rwxr-x--- 1 eliu da  6332 Nov 30 13:09 run_bufr2ioda.py.emily
```

The following error received while running the gdasprepatmiodaobs.

```
Traceback (most recent call last):
  File "/work2/noaa/da/eliu/gdas-validation/global-workflow/ush/python/wxflow/executable.py", line 203, in __call__
    proc = subprocess.Popen(cmd, stdin=istream, stderr=estream, stdout=ostream, env=env, close_fds=False)
  File "/work2/noaa/da/python/opt/core/miniconda3/4.6.14/envs/gdasapp/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/work2/noaa/da/python/opt/core/miniconda3/4.6.14/envs/gdasapp/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/work2/noaa/da/eliu/gdas-validation/global-workflow/sorc/gdas.cd/ush/ioda/bufr2ioda/bufr2ioda_subpfl_argo_profiles.py'

During handling of the above exception, another exception occurred:
```

**Comment by RussTreadon-NOAA** [comment]
Create branch [`feature/chmod`](https://github.com/NOAA-EMC/GDASApp/tree/feature/chmod) in which to correct this problem.

**Comment by RussTreadon-NOAA** [comment]
`chmod 755 bufr2ioda_subpfl_argo_profiles.py` to make permission consistent with other scripts in `ush/ioda/bufr2ioda`.  Done at 78bda90.

**Comment by ShastriPaturi** [comment]
@RussTreadon-NOAA and @emilyhcliu I will keep this in mind for my subsequent PRs.
