### ISSUE TITLE
atmospheric bufr2ioda converter fails when expected subsets not found

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/GDASApp#898]
The 2021032318 gdasprepatmiodaobs job failed when `bufr2ioda_satwind_amv_goes.py` did not find expected subsets in the input bufr dump file.   Below is a traceback from the job log file
```
^[[38;21m2024-02-01 16:44:12,590 - INFO     - run_bufr2ioda.py: Convert satwind_amv_goes...^[[0m
^[[38;21m2024-02-01 16:44:12,590 - INFO     - gen_bufr2ioda_json.py: Using /scratch1/NCEPDEV/da/role.jedipara/git/global-workflow/atmos/sorc/gdas.cd/parm/ioda/bufr2ioda/bufr2ioda_satwind_amv_goes.json as input^[[0m
^[[38;21m2024-02-01 16:44:12,602 - INFO     - gen_bufr2ioda_json.py: Wrote to /scratch1/NCEPDEV/stmp2/role.jedipara/RUNDIRS/prjedi/prepatmobs.27933/satwind_amv_goes_2021032318.json^[[0m

...

^[[38;21m2024-02-01 16:44:13,964 - INFO     - BUFR2IODA_satwind_amv_goes.py: sensor_name = ABI^[[0m
^[[38;21m2024-02-01 16:44:13,964 - INFO     - BUFR2IODA_satwind_amv_goes.py: sensor_full_name = Advanced Baseline Imager^[[0m
^[[38;21m2024-02-01 16:44:13,964 - INFO     - BUFR2IODA_satwind_amv_goes.py: sensor_id = 617^[[0m
^[[38;21m2024-02-01 16:44:13,964 - INFO     - BUFR2IODA_satwind_amv_goes.py: reference_time = 2021-03-23T18:00:00Z^[[0m
^[[38;21m2024-02-01 16:44:13,964 - INFO     - BUFR2IODA_satwind_amv_goes.py: Making QuerySet^[[0m
^[[38;21m2024-02-01 16:44:13,968 - INFO     - BUFR2IODA_satwind_amv_goes.py: Executing QuerySet to get ResultSet^[[0m

...

PRE-MAIN-ERROR Exception: BadValue: No valid BUFR subsets were found from your queries! Please make sure you are querying for valid subsets that exist in /scratch1/NCEPDEV/global/glopara/dump\
/gdas.20210323/18/atmos/gdas.t18z.satwnd.tm00.bufr_d. Otherwise there might be a problem with the BUFR file (no subsets).
Traceback (most recent call last):
  File "/scratch1/NCEPDEV/da/role.jedipara/git/global-workflow/atmos/sorc/gdas.cd/ush/ioda/bufr2ioda/bufr2ioda_satwind_amv_goes.py", line 472, in <module>
    bufr_to_ioda(config, logger)
  File "/scratch1/NCEPDEV/da/role.jedipara/git/global-workflow/atmos/sorc/gdas.cd/ush/ioda/bufr2ioda/bufr2ioda_satwind_amv_goes.py", line 164, in bufr_to_ioda
    r = f.execute(q)
RuntimeError: BadValue: No valid BUFR subsets were found from your queries! Please make sure you are querying for valid subsets that exist in /scratch1/NCEPDEV/global/glopara/dump/gdas.20210323/18/atmos/gdas.t18z.satwnd.tm00.bufr_d. Otherwise there might be a problem with the BUFR file (no subsets).

...

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/scratch1/NCEPDEV/da/python/opt/core/miniconda3/4.6.14/envs/gdasapp/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/scratch1/NCEPDEV/da/python/opt/core/miniconda3/4.6.14/envs/gdasapp/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/scratch1/NCEPDEV/da/role.jedipara/git/global-workflow/atmos/ush/run_bufr2ioda.py", line 28, in mp_bufr_converter
    cmd()
  File "/scratch1/NCEPDEV/da/role.jedipara/git/global-workflow/atmos/ush/python/wxflow/executable.py", line 230, in __call__
    raise ProcessError(f"Command exited with status {proc.returncode}:", long_msg)
wxflow.executable.ProcessError: Command exited with status 1:
'/scratch1/NCEPDEV/da/role.jedipara/git/global-workflow/atmos/sorc/gdas.cd/ush/ioda/bufr2ioda/bufr2ioda_satwind_amv_goes.py' '-c' '/scratch1/NCEPDEV/stmp2/role.jedipara/RUNDIRS/prjedi/prepatmobs.27933/satwind_amv_goes_2021032318.json'
"""
```

To sidestep this problem, `bufr2ioda_satwind_amv_goes.py` was renamed `skip_bufr2ioda_satwind_amv_goes.py` and 2021032318 gdasprepatmiodaobs rerun.  The rerun completed without error.  After this, `skip_bufr2ioda_satwind_amv_goes.py` was moved back to `bufr2ioda_satwind_amv_goes.py`.   This is not a solution.

There will be times in an operational setting when an expected bufr dump file or expected subsets in a bufr dump file are not present.  Should the bufr2ioda converters be expected to handle either of these situations or do we handle this possibility elsewhere in the workflow?

This issue is opened to document this problem and develop a robust solution.

**Comment by RussTreadon-NOAA** [comment]
**2021032318 failure**
For this cycle there are **no** GOES AMVs in `gdas.t18z.satwnd.tm00.bufr_d` as confirmed by the SATWND listing in `gdas.t18z.status.tm00.bufr_d`
```
         ---> 005.044 (in satwnd) SAT. ID  173 has    46154 reports
         ---> 005.045 (in satwnd) SAT. ID  173 has     3670 reports
         ---> 005.046 (in satwnd) SAT. ID  173 has    57437 reports
         ---> 005.067 (in satwnd) SAT. ID   55 has    62305 reports
         ---> 005.067 (in satwnd) SAT. ID   70 has    68163 reports
         ---> 005.068 (in satwnd) SAT. ID   55 has    18207 reports
         ---> 005.068 (in satwnd) SAT. ID   70 has    94002 reports
         ---> 005.069 (in satwnd) SAT. ID   55 has   127814 reports
         ---> 005.069 (in satwnd) SAT. ID   70 has   124422 reports
         ---> 005.070 (in satwnd) SAT. ID  783 has     2726 reports
         ---> 005.070 (in satwnd) SAT. ID  784 has      386 reports
         ---> 005.080 (in satwnd) SAT. ID    3 has     6928 reports
         ---> 005.080 (in satwnd) SAT. ID    4 has     6602 reports
         ---> 005.080 (in satwnd) SAT. ID  206 has      540 reports
         ---> 005.080 (in satwnd) SAT. ID  209 has     1124 reports
         ---> 005.080 (in satwnd) SAT. ID  223 has      605 reports
         ---> 005.091 (in satwnd) SAT. ID  224 has    21198 reports
         ---> 005.091 (in satwnd) SAT. ID  225 has    24374 reports
         ---> 005.072 (in satwnd) SAT. ID  854 has    71619 reports
```
The traceback in `gdasprepatmiodaobs.log` points to line 164 of `bufr2ioda_satwind_amv_goes.py`.  This is the `f.execute` line below
```
    # ==============================================================
    # Open the BUFR file and execute the QuerySet to get ResultSet
    # Use the ResultSet returned to get numpy arrays of the data
    # ==============================================================
    start_time = time.time()

    logger.info('Executing QuerySet to get ResultSet')
    with bufr.File(DATA_PATH) as f:
        r = f.execute(q)
```
Based on the log file, `bufr2ioda_satwind_amv_goes.py` is returning a non-zero exit code
```
wxflow.executable.ProcessError: Command exited with status 1:
'/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/work/sorc/gdas.cd/ush/ioda/bufr2ioda/bufr2ioda_satwind_amv_goes.py' '-c' '/scratch1/NCEPDEV/stmp2/Russ.Treadon/RUNDIRS/prci/prepatmobs.158050/satwind_amv_goes_2021032318.json'
```
Is there some we can avoid the non-zero exit code or at least have it not kill the job?

**Comment by RussTreadon-NOAA** [comment]
OK, the message
```
RuntimeError: BadValue: No valid BUFR subsets were found from your queries! Please make sure you are querying for valid subsets that exist in /scratch1/NCEPDEV/global/glopara/dump/gdas.20210323/18/atmos/gdas.t18z.satwnd.tm00.bufr_d. Otherwise there might be a problem with the BUFR file (no subsets).
```
originates from `sorc/iodaconv/src/bufr/BufrParser/Query/DataProvider/DataProvider.cpp`   Given this, I'm not sure where we should make a change.   Do we 
- generate a non-fatal error from `DataProvider.cpp`
- add checks in `bufr2ioda_satwnd_amv_goes.py` to exit before we get to the query
- something else?

Tagging @BrettHoover-NOAA , @rmclaren , @CoryMartin-NOAA

**Comment by CoryMartin-NOAA** [comment]
We should be able to catch the error in the goes amv python script. 
Wrap it in a
`try:`
`except X:`
where X is the kind of exception we are expecting

**Comment by rmclaren** [comment]
Cory's solution should work.

**Comment by RussTreadon-NOAA** [comment]
Thank you @CoryMartin-NOAA and @rmclaren for your guidance.
```
    logger.info('Executing QuerySet to get ResultSet')
    with bufr.File(DATA_PATH) as f:
        try:
            r = f.execute(q)
        except:
            logger.info(f'Querried subset not found')
            return

    # MetaData
    satid = r.get('satelliteId')
```
works.   

With the above the 2021032318 case generates
```
(gdasapp) Hera(hfe05):/scratch1/NCEPDEV/stmp2/Russ.Treadon/RUNDIRS/prci/prepatmobs.104334$ /scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/work/sorc/gdas.cd/ush/ioda/bufr2ioda/bufr2ioda_satwind_amv_goes.py -c ./satwind_amv_goes_2021032318.json
2024-02-27 20:06:41,443 - INFO     - BUFR2IODA_satwind_amv_goes.py: sensor_name = ABI
2024-02-27 20:06:41,443 - INFO     - BUFR2IODA_satwind_amv_goes.py: sensor_full_name = Advanced Baseline Imager
2024-02-27 20:06:41,443 - INFO     - BUFR2IODA_satwind_amv_goes.py: sensor_id = 617
2024-02-27 20:06:41,443 - INFO     - BUFR2IODA_satwind_amv_goes.py: reference_time = 2021-03-23T18:00:00Z
2024-02-27 20:06:41,443 - INFO     - BUFR2IODA_satwind_amv_goes.py: Making QuerySet
2024-02-27 20:06:41,445 - INFO     - BUFR2IODA_satwind_amv_goes.py: Executing QuerySet to get ResultSet
PRE-MAIN-ERROR Exception: BadValue: No valid BUFR subsets were found from your queries! Please make sure you are querying for valid subsets that exist in /scratch1/NCEPDEV/global/glopara/dump/gdas.20210323/18/atmos/gdas.t18z.satwnd.tm00.bufr_d. Otherwise there might be a problem with the BUFR file (no subsets).
2024-02-27 20:06:41,716 - INFO     - BUFR2IODA_satwind_amv_goes.py: Querried subset not found
2024-02-27 20:06:41,716 - INFO     - BUFR2IODA_satwind_amv_goes.py: Total running time: 0.27774691581726074 seconds
```

The same script generates the following for 2024022318 (a case with GOES AMVs)
```
(gdasapp) Hera(hfe05):/scratch1/NCEPDEV/stmp2/Russ.Treadon/RUNDIRS/prci/prepatmobs.104334$ /scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/work/sorc/gdas.cd/ush/ioda/bufr2ioda/bufr2ioda_satwind_amv_goes.py -c ./satwind_amv_goes_2024022318.json
2024-02-27 20:07:31,082 - INFO     - BUFR2IODA_satwind_amv_goes.py: sensor_name = ABI
2024-02-27 20:07:31,082 - INFO     - BUFR2IODA_satwind_amv_goes.py: sensor_full_name = Advanced Baseline Imager
2024-02-27 20:07:31,082 - INFO     - BUFR2IODA_satwind_amv_goes.py: sensor_id = 617
2024-02-27 20:07:31,082 - INFO     - BUFR2IODA_satwind_amv_goes.py: reference_time = 2024-02-23T18:00:00Z
2024-02-27 20:07:31,082 - INFO     - BUFR2IODA_satwind_amv_goes.py: Making QuerySet
2024-02-27 20:07:31,084 - INFO     - BUFR2IODA_satwind_amv_goes.py: Executing QuerySet to get ResultSet
2024-02-27 20:10:31,538 - INFO     - BUFR2IODA_satwind_amv_goes.py: Processing time for executing QuerySet to get ResultSet : 180.35085010528564 seconds
2024-02-27 20:10:31,709 - INFO     - BUFR2IODA_satwind_amv_goes.py: Creating derived variables
2024-02-27 20:10:32,348 - INFO     - BUFR2IODA_satwind_amv_goes.py: Processing time for creating derived variables : 0.6391744613647461 seconds
2024-02-27 20:10:32,348 - INFO     - BUFR2IODA_satwind_amv_goes.py: Create IODA ObsSpace and Write IODA output based on satellite ID
2024-02-27 20:10:32,492 - INFO     - BUFR2IODA_satwind_amv_goes.py: Number of Unique satellite identifiers: 2
2024-02-27 20:10:32,585 - INFO     - BUFR2IODA_satwind_amv_goes.py: Unique satellite identifiers: [270 272]
2024-02-27 20:10:32,804 - INFO     - BUFR2IODA_satwind_amv_goes.py: Create output file : /scratch1/NCEPDEV/stmp2/Russ.Treadon/COMROOT/prci/gdas.20240223/18/obs_test/gdas.t18z.satwnd.abi_goes-16.tm00.nc
2024-02-27 20:10:36,714 - INFO     - BUFR2IODA_satwind_amv_goes.py: Create output file : /scratch1/NCEPDEV/stmp2/Russ.Treadon/COMROOT/prci/gdas.20240223/18/obs_test/gdas.t18z.satwnd.abi_goes-18.tm00.nc
2024-02-27 20:10:39,923 - INFO     - BUFR2IODA_satwind_amv_goes.py: All Done!
2024-02-27 20:10:39,923 - INFO     - BUFR2IODA_satwind_amv_goes.py: Total number of observation processed : 2827703
2024-02-27 20:10:46,680 - INFO     - BUFR2IODA_satwind_amv_goes.py: Total running time: 195.60101509094238 seconds
```

**Comment by RussTreadon-NOAA** [comment]
`pycodestyle` throws error
```
checking ./ush/ioda/bufr2ioda/bufr2ioda_satwind_amv_goes.py
./ush/ioda/bufr2ioda/bufr2ioda_satwind_amv_goes.py:166:9: E722 do not use bare 'except'
```
I understand that I need to add _something_ on the `except` line in `bufr2ioda_satwind_amv_goes.py`
```
    with bufr.File(DATA_PATH) as f:
        try:
            r = f.execute(q)
        except:
            logger.info(f'Querried subset not found')
            return
```
I don't know what _something_ is.  Suggestions?

**Comment by BrettHoover-NOAA** [comment]
Here's a very short explanation of how to properly avoid the bare except
issue: https://www.30secondsofcode.org/python/s/bare-except/

**Comment by BrettHoover-NOAA** [comment]
You could use

except RuntimeError:

which is a pre-built exception error for a general failure, other types are
here: https://docs.python.org/3/library/exceptions.html

**Comment by RussTreadon-NOAA** [comment]
Thanks, @BrettHoover-NOAA !  
The following works
```
     with bufr.File(DATA_PATH) as f:
         try:
             r = f.execute(q)
         except RuntimeError:
             logger.info(f'Querried subset not found')
             return
```
and passes `pycodestyle`

**Comment by rmclaren** [comment]
You could do something like this:

```python
try:
    r = f.execute(q)
except Exception as err:
    print(err)
    print(type(err)) 
```

This should give you the error type and make sure the error message is right.

My guess you will you will end up with something like this:

```python
try:
    r = f.execute(q)
except Exception as err:
    logger.info(err)
    return
```

**Comment by RussTreadon-NOAA** [comment]
Thank you @rmclaren for input.  I added your suggested changes to `bufr2ioda_satwind_amv_goes.py`.  

`err` winds up holding 
```
BadValue: No valid BUFR subsets were found from your queries! Please make sure you are querying for valid subsets that exist in /scratch1/NCEPDEV/global/glopara/dump/gdas.20210323/18/atmos/gdas.t18z.satwnd.tm00.bufr_d. Otherwise there might be a problem with the BUFR file (no subsets).
```
The type for `err` is ` <class 'RuntimeError'>`.   

I'm learning a lot from @CoryMartin-NOAA , @BrettHoover-NOAA , and you.
